sudo: required

language: python

cache:
    apt: true
    directories:
        - $HOME/.cache/pip

addons:
    apt:
        packages:
            - libatlas3gf-base
            - libatlas-dev
            - python-scipy

python:
    - "2.7"
    - "3.5"
    - "nightly"
install:
    - source .travis_install.sh
script: nosetests

