sudo: true

language: python

os:
    - linux
    - osx

cache:
    apt: true
    directories:
        - $HOME/.cache/pip

addons:
    apt:
        packages:
            - libatlas3gf-base
            - libatlas-dev
            - python-scipy
            - python-sklearn

python:
    - "2.7"

install:
    - source .travis_install.sh

script: nosetests

