sudo: true
dist: trusty

language: python

os:
    - linux

env:
    matrix:
        - TASK=lint
        - TASK=nosetests

cache:
    apt: true
    directories:
        - $HOME/.cache/pip

addons:
    apt:
        packages:
            - libatlas3gf-base
            - libatlas-dev
            - python-scipy

python:
    - "2.7"

install:
    - source scripts/travis_install.sh

script: source scripts/run_tests.sh
