sudo: false

language: python

cache:
    apt: true
    directories:
        - $HOME/.cache/pip

python:
    - "2.7"
    - "3.5"
    - "nightly"
install:
    - pip install --user sklearn scipy numpy
    - pip install --user https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
    - pip install --user nose
script: nosetests

