name: ARM CD

on:
  push:
    tags: v2.*
  schedule:
    cron: '0 8 * * *'

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    strategy:
      matrix:
        pyver: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - name: Clean repository
        shell: bash
        run: find /home/ubuntu/actions-runner/_work/tensorflow/tensorflow/. -name . -o -prune -exec sudo rm -rf -- {} + || true
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and test pip wheel
        shell: bash
        run: |
          CI_DOCKER_BUILD_EXTRA_PARAMS='--build-arg py_major_minor_version=${{ matrix.pyver }}' \
          ./tensorflow/tools/ci_build/ci_build.sh cpu.arm64 bash tensorflow/tools/ci_build/rel/ubuntu/cpu_arm64_pip.sh
      - name: Upload pip wheel to PyPI
        shell: bash
        run: python3 -m twine upload --verbose /home/ubuntu/actions-runner/_work/tensorflow/tensorflow/whl/* -u "__token__" -p ${{ secrets.AWS_PYPI_ACCOUNT_TOKEN }}
