name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "/home/runner/.cache/bazel"
        key: bazelcache
    
    - name: Install dependenceies
      run: |
        pip install -U pip numpy wheel
        pip install -U keras_preprocessing --no-deps

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"


    - name: Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //tensorflow/tools/pip_package:build_pip_package
